parcelRequire=function(e,r,n,t){var i="function"==typeof parcelRequire&&parcelRequire,o="function"==typeof require&&require;function u(n,t){if(!r[n]){if(!e[n]){var f="function"==typeof parcelRequire&&parcelRequire;if(!t&&f)return f(n,!0);if(i)return i(n,!0);if(o&&"string"==typeof n)return o(n);var c=new Error("Cannot find module '"+n+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[n][1][r]||r};var l=r[n]=new u.Module(n);e[n][0].call(l.exports,p,l,l.exports,this)}return r[n].exports;function p(e){return u(p.resolve(e))}}u.isParcelRequire=!0,u.Module=function(e){this.id=e,this.bundle=u,this.exports={}},u.modules=e,u.cache=r,u.parent=i,u.register=function(r,n){e[r]=[function(e,r){r.exports=n},{}]};for(var f=0;f<n.length;f++)u(n[f]);if(n.length){var c=u(n[n.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=c:"function"==typeof define&&define.amd?define(function(){return c}):t&&(this[t]=c)}return u}({"bEwO":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var t="display: none !important",e={".moments.js-moments-tab":t,"[data-promoted='true']":t},r="visibility: hidden !important",o=exports.hideDOMElement=function(t,o){var i=!0,n=!1,a=void 0;try{for(var l,s=t[Symbol.iterator]();!(i=(l=s.next()).done);i=!0){l.value.style=e[o]||r}}catch(t){n=!0,a=t}finally{try{!i&&s.return&&s.return()}finally{if(n)throw a}}};
},{}],"/I9u":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=function(){},t={overrideSkip:!1,disconnect:!0},n=exports.observeElement=function(n){var o=n.selector,r=n.options,i=void 0===r?t:r,c=n.callback,l=void 0===c?e:c,a=document.querySelectorAll(o);if(null!=a&&a.length&&a.length>0)l(a,o);else{var d=i.disconnect,s=void 0===d||d,u=i.overrideSkip,v=void 0!==u&&u,f=!1;new MutationObserver(function(e,t){var n=[];e.forEach(function(e){var r=e.addedNodes,i=!0,c=!1,a=void 0;try{for(var d,u=r[Symbol.iterator]();!(i=(d=u.next()).done);i=!0){var h=d.value;h.matches&&h.matches(o)&&n.push(h)}}catch(e){c=!0,a=e}finally{try{!i&&u.return&&u.return()}finally{if(c)throw a}}n.length&&(s&&t.disconnect(),window.requestAnimationFrame(function(){v?l(n,o):f||(f=!0,l(n))}))})}).observe(document.documentElement,{childList:!0,subtree:!0})}};
},{}],"XJo1":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.hideWhoToFollow=void 0;var e=require("./hide-element"),o=require("./observe-element"),r=exports.hideWhoToFollow=function(){var r=function(r){(0,o.observeElement)({selector:r,callback:function(o){(0,e.hideDOMElement)(o,r)}})},t=!0,l=!1,i=void 0;try{for(var n,u=[".module.wtf-module.js-wtf-module",".module.Footer"][Symbol.iterator]();!(t=(n=u.next()).done);t=!0){r(n.value)}}catch(e){l=!0,i=e}finally{try{!t&&u.return&&u.return()}finally{if(l)throw i}}};
},{"./hide-element":"bEwO","./observe-element":"/I9u"}],"nfGp":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.hideTrends=void 0;var e=require("./hide-element"),r=require("./observe-element"),t=exports.hideTrends=function(){(0,r.observeElement)({selector:".module.Trends.trends",callback:function(r){(0,e.hideDOMElement)(r,".module.Trends.trends")}})};
},{"./hide-element":"bEwO","./observe-element":"/I9u"}],"axFg":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.hideFeedProfile=void 0;var e=require("./hide-element"),r=require("./observe-element"),o=exports.hideFeedProfile=function(){var o=".dashboard.dashboard-left";(0,r.observeElement)({selector:o,callback:function(r){(0,e.hideDOMElement)(r,o)}})};
},{"./hide-element":"bEwO","./observe-element":"/I9u"}],"tSSV":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.addLikesTabToNavBar=exports.hideMomentsTab=void 0;var e=require("./hide-element"),t=require("./observe-element"),n="#__like_button_tab",s=exports.hideMomentsTab=function(){(0,t.observeElement)({selector:".moments.js-moments-tab",callback:function(t){(0,e.hideDOMElement)(t,".moments.js-moments-tab")}})},a=exports.addLikesTabToNavBar=function(){null===document.querySelector(n)&&(0,t.observeElement)({selector:"#global-actions",options:{skipIfAlreadyPresent:!0},callback:o})},o=function(e){var t=e[0],n=document.createElement("li"),s=document.createElement("a");s.setAttribute("href","/i/likes"),s.setAttribute("role","button"),s.setAttribute("data-nav","favorites"),s.setAttribute("class","js-nav js-tooltip js-dynamic-tooltip"),s.setAttribute("id","__like_button_tab"),s.setAttribute("data-placement","bottom"),n.setAttribute("style","cursor: pointer;");var a=document.createElement("span");a.setAttribute("class","Icon Icon--heart Icon--large");var o=document.createElement("span");o.setAttribute("class","text"),o.innerText="Likes",s.appendChild(a),s.appendChild(o),n.appendChild(s),t.appendChild(n)};
},{"./hide-element":"bEwO","./observe-element":"/I9u"}],"1M5n":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.loadNewTweets=exports.hidePromotedTweets=void 0;var e=require("./hide-element"),t=require("./observe-element"),o=exports.hidePromotedTweets=function(){(0,t.observeElement)({selector:"[data-promoted='true']",options:{disconnect:!1},callback:function(t){(0,e.hideDOMElement)(t,"[data-promoted='true']")}})},r=exports.loadNewTweets=function(){(0,t.observeElement)({selector:".new-tweets-bar.js-new-tweets-bar",options:{disconnect:!1,overrideSkip:!0},callback:function(e){document.body.getBoundingClientRect().top>=-20&&e[0].click()}})};
},{"./hide-element":"bEwO","./observe-element":"/I9u"}],"pILq":[function(require,module,exports) {
"use strict";var e=require("./features/who-to-follow"),r=require("./features/trends"),t=require("./features/feed-profile"),o=require("./features/nav-bar"),s=require("./features/tweets"),a=function(){(0,e.hideWhoToFollow)(),(0,r.hideTrends)(),(0,t.hideFeedProfile)(),(0,o.hideMomentsTab)(),(0,o.addLikesTabToNavBar)(),(0,s.hidePromotedTweets)(),(0,s.loadNewTweets)()};chrome.runtime.onMessage.addListener(function(e,r,t){"Twitter URL has changed"===e.message&&a()}),0===document.querySelectorAll(".logged-out").length&&a();
},{"./features/who-to-follow":"XJo1","./features/trends":"nfGp","./features/feed-profile":"axFg","./features/nav-bar":"tSSV","./features/tweets":"1M5n"}]},{},["pILq"], null)
//# sourceMappingURL=/content.map